version: '3.8'

services:
  php:
    build:
      context: .
    container_name: php_apache
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/httpd.conf:/etc/apache2/httpd.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: unless-stopped
    # ports:
    #   - "11211:11211"

  # mysql:
  #   image: mysql:8
  #   container_name: mysql_db
  #   restart: unless-stopped
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234567890
  #     MYSQL_DATABASE: tv_cultura
  #     MYSQL_USER: tv_cultura
  #     MYSQL_PASSWORD: 1234567890

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: your_root_password
  #   depends_on:
  #     - mysql

# volumes:
#   mysql:
